-- Crear usuario postgres si no existe
DO
$$
BEGIN
   IF NOT EXISTS (SELECT FROM pg_catalog.pg_roles WHERE rolname = 'postgres') THEN
      CREATE ROLE postgres WITH LOGIN PASSWORD 'Qazwsx12' SUPERUSER;
   END IF;
END
$$;

-- Crear usuario taskmanageruser si no existe
DO
$$
BEGIN
   IF NOT EXISTS (SELECT FROM pg_catalog.pg_roles WHERE rolname = 'taskmanageruser') THEN
      CREATE ROLE "taskmanageruser" WITH LOGIN PASSWORD 'Qazwsx12';
   END IF;
END
$$;

-- Crear base de datos y asignar propietario
SELECT 'CREATE DATABASE "dbtaskmanager" OWNER "taskmanageruser"'
WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = 'dbtaskmanager')\gexec

GRANT ALL PRIVILEGES ON DATABASE "dbtaskmanager" TO "taskmanageruser";
GRANT CONNECT ON DATABASE "dbtaskmanager" TO "taskmanageruser";

\connect dbtaskmanager

-- Una vez conectados a la base de datos, asignamos permisos al usuario taskmanageruser para el esquema public y las tablas que se creen en el futuro
GRANT USAGE ON SCHEMA public TO "taskmanageruser";
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO "taskmanageruser";
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO "taskmanageruser";


-- Coloca las tabla de tasks manager en el esquema public y asigna permisos
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO "taskmanageruser";
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO "taskmanageruser";
GRANT ALL PRIVILEGES ON ALL FUNCTIONS IN SCHEMA public TO "taskmanageruser";
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL PRIVILEGES ON TABLES TO "taskmanageruser";
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL PRIVILEGES ON SEQUENCES TO "taskmanageruser";
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL PRIVILEGES ON FUNCTIONS TO "taskmanageruser";   

CREATE Table IF Not Exists tasks (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    titulo VARCHAR(255) COLLATE pg_catalog."default" NOT NULL,
    contenido TEXT COLLATE pg_catalog."default",
    completada BOOLEAN DEFAULT FALSE,
    deadline TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT tasks_pkey PRIMARY KEY (id)
);

ALTER TABLE IF EXISTS public.tasks
    OWNER to "taskmanageruser";



