import logging
import os
import time
from datetime import datetime, timezone
from typing import Any, Generator

import psycopg2
from psycopg2 import sql
from psycopg2.extras import RealDictCursor


logger = logging.getLogger("api.db")


def _get_env(*keys: str, default: str) -> str:
    for key in keys:
        value = os.getenv(key)
        if value:
            return value
    return default


def _connect_with_retries(host: str, port: int, db_name: str, user: str, password: str):
    max_retries = int(_get_env("POSTGRES_CONNECT_RETRIES", default="10"))
    retry_delay_seconds = float(_get_env("POSTGRES_RETRY_DELAY_SECONDS", default="1"))

    for attempt in range(1, max_retries + 1):
        try:
            logger.info(
                "event=db_connect host=%s port=%s db=%s user=%s attempt=%s/%s",
                host,
                port,
                db_name,
                user,
                attempt,
                max_retries,
            )
            return psycopg2.connect(
                host=host,
                port=port,
                dbname=db_name,
                user=user,
                password=password,
            )
        except psycopg2.OperationalError:
            if attempt == max_retries:
                raise

            sleep_seconds = retry_delay_seconds * attempt
            logger.warning(
                "event=db_connect_retry host=%s db=%s attempt=%s/%s wait_seconds=%.2f",
                host,
                db_name,
                attempt,
                max_retries,
                sleep_seconds,
            )
            time.sleep(sleep_seconds)


def get_postgres_connection():
    host = _get_env("POSTGRES_HOST", "DB_POSTGRESDB_HOST", default="postgres")
    port = int(_get_env("POSTGRES_PORT", "DB_POSTGRESDB_PORT", default="5432"))
    db_name = _get_env("POSTGRES_DB_NAME", "DB_POSTGRESDB_DATABASE", default="dbtaskmanager")
    user = _get_env("POSTGRES_USER_NAME", "DB_POSTGRESDB_USER", default="taskmanageruser")
    password = _get_env("POSTGRES_PASSWORD_VALUE", "DB_POSTGRESDB_PASSWORD", default="Qazwsx12")
    return _connect_with_retries(host, port, db_name, user, password)

def get_postgres_connection_server(host:str):
    host = _get_env("POSTGRES_HOST", "DB_POSTGRESDB_HOST", default=host)
    port = int(_get_env("POSTGRES_PORT", "DB_POSTGRESDB_PORT", default="5432"))
    db_name = _get_env("POSTGRES_DB_NAME", "DB_POSTGRESDB_DATABASE", default="dbtaskmanager")
    user = _get_env("POSTGRES_USER_NAME", "DB_POSTGRESDB_USER", default="taskmanageruser")
    password = _get_env("POSTGRES_PASSWORD_VALUE", "DB_POSTGRESDB_PASSWORD", default="Qazwsx12")
    return _connect_with_retries(host, port, db_name, user, password)

# Crea la tabla "tasks" en la base de datos si no existe, con las columnas id, titulo, contenido, completada, deadline, created_at y updated_at. La columna id es una clave primaria autoincremental, titulo es un campo de texto obligatorio, contenido es un campo de texto opcional, completada es un campo booleano que indica si la tarea está completada o no (por defecto es false), deadline es un campo de fecha y hora opcional que indica la fecha límite para completar la tarea, created_at es un campo de fecha y hora que se establece automáticamente con la fecha y hora actual cuando se crea la tarea, y updated_at es un campo de fecha y hora que se establece automáticamente con la fecha y hora actual cada vez que se actualiza la tarea.
# si el script de inicio falla al crear el contenedor de postgres 
def init_db() -> None:
    query = """
    CREATE TABLE IF NOT EXISTS tasks (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        titulo VARCHAR(255) NOT NULL,
        contenido TEXT,
        completada BOOLEAN DEFAULT FALSE,
        deadline TIMESTAMPTZ,
        created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
        updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
    )
    """
    with get_postgres_connection() as connection:
        with connection.cursor() as cursor:
            cursor.execute(query)
        connection.commit()
    logger.info("event=init_db table=tasks status=ready")

# Carga la base de datos 
def get_db() -> Generator[Any, None, None]:
    connection = get_postgres_connection()
    try:
        yield connection
    finally:
        connection.close()

# IS done: Funciones para el manejo de los registros de la tabla "tasks": 
# insert_record, get_record_by_id, get_all_records, 
# delete_record, get_expired_tasks, count_overdue_tasks y update_record. 
# Estas funciones deben utilizar consultas SQL parametrizadas para evitar 
# inyecciones SQL y deben manejar adecuadamente las conexiones a la base
# de datos utilizando el contexto proporcionado por get_db().
def insert_record(table: str, data: dict[str, Any]) -> dict[str, Any]:
    if not data:
        raise ValueError("El cuerpo 'data' no puede estar vacio.")

    columns = list(data.keys())
    values = [data[column] for column in columns]

    query = sql.SQL(
        "INSERT INTO {table} ({fields}) VALUES ({placeholders}) RETURNING *"
    ).format(
        table=sql.Identifier(table),
        fields=sql.SQL(", ").join(sql.Identifier(column) for column in columns),
        placeholders=sql.SQL(", ").join(sql.Placeholder() for _ in columns),
    )

    with get_postgres_connection() as connection:
        with connection.cursor(cursor_factory=RealDictCursor) as cursor:
            cursor.execute(query, values)
            created_row = cursor.fetchone()
        connection.commit()

    logger.info("event=db_insert table=%s created=%s", table, bool(created_row))

    return dict(created_row) if created_row else {}


def get_record_by_id(table: str, record_id: Any, id_column: str = "id") -> dict[str, Any] | None:
    query = sql.SQL("SELECT * FROM {table} WHERE {id_column} = %s").format(
        table=sql.Identifier(table),
        id_column=sql.Identifier(id_column),
    )

    with get_postgres_connection() as connection:
        with connection.cursor(cursor_factory=RealDictCursor) as cursor:
            cursor.execute(query, [record_id])
            row = cursor.fetchone()

    logger.info("event=db_get_by_id table=%s id_column=%s found=%s", table, id_column, bool(row))

    return dict(row) if row else None


def get_all_records(table: str) -> list[dict[str, Any]]:
    query = sql.SQL("SELECT * FROM {table}").format(table=sql.Identifier(table))

    with get_postgres_connection() as connection:
        with connection.cursor(cursor_factory=RealDictCursor) as cursor:
            cursor.execute(query)
            rows = cursor.fetchall()

    logger.info("event=db_get_all table=%s count=%s", table, len(rows))

    return [dict(row) for row in rows]


def delete_record(table: str, record_id: Any, id_column: str = "id") -> bool:
    query = sql.SQL("DELETE FROM {table} WHERE {id_column} = %s RETURNING {id_column}").format(
        table=sql.Identifier(table),
        id_column=sql.Identifier(id_column),
    )

    with get_postgres_connection() as connection:
        with connection.cursor() as cursor:
            cursor.execute(query, [record_id])
            deleted = cursor.fetchone()
        connection.commit()

    logger.info("event=db_delete table=%s id_column=%s deleted=%s", table, id_column, bool(deleted))

    return bool(deleted)


def get_expired_tasks() -> list[dict[str, Any]]:
    query = """
    SELECT *
    FROM tasks
    WHERE deadline IS NOT NULL
      AND deadline < %s
    ORDER BY deadline ASC
    """

    with get_postgres_connection() as connection:
        with connection.cursor(cursor_factory=RealDictCursor) as cursor:
            cursor.execute(query, [datetime.now(timezone.utc)])
            rows = cursor.fetchall()

    logger.info("event=db_get_expired_tasks count=%s", len(rows))

    return [dict(row) for row in rows]


def count_overdue_tasks() -> int:
    query = """
    SELECT COUNT(*) AS overdue
    FROM tasks
    WHERE deadline IS NOT NULL
      AND deadline < %s
      AND completada = FALSE
    """

    with get_postgres_connection() as connection:
        with connection.cursor(cursor_factory=RealDictCursor) as cursor:
            cursor.execute(query, [datetime.now(timezone.utc)])
            row = cursor.fetchone()

    logger.info("event=db_count_overdue overdue=%s", int(row["overdue"]) if row else 0)

    return int(row["overdue"]) if row else 0

# Actualiza un registro en la tabla especificada por el id_column (por defecto "id") 
# con los datos proporcionados en el diccionario data.
# id_column se utiliza para identificar el registro a actualizar. 
# La función devuelve el registro actualizado como un diccionario o None si no se encontró ningún registro con el id especificado. Si el cuerpo data está vacío, se lanza un ValueError. 
def update_record(table: str, record_id: Any, data: dict[str, Any], id_column: str = "id") -> dict[str, Any] | None:
    if record_id is None:
        raise ValueError("El campo 'id' es obligatorio.")

    if not data:
        raise ValueError("El cuerpo 'data' no puede estar vacio.")

    assignments = [
        sql.SQL("{field} = {placeholder}").format(
            field=sql.Identifier(column),
            placeholder=sql.Placeholder(),
        )
        for column in data.keys()
    ]

    query = sql.SQL(
        "UPDATE {table} SET {assignments} WHERE {id_column} = {id_placeholder} RETURNING *"
    ).format(
        table=sql.Identifier(table),
        assignments=sql.SQL(", ").join(assignments),
        id_column=sql.Identifier(id_column),
        id_placeholder=sql.Placeholder(),
    )

    with get_postgres_connection() as connection:
        with connection.cursor(cursor_factory=RealDictCursor) as cursor:
            cursor.execute(query, [*data.values(), record_id])
            updated_row = cursor.fetchone()
        connection.commit()

    logger.info("event=db_update table=%s id_column=%s updated=%s", table, id_column, bool(updated_row))

    return dict(updated_row) if updated_row else None